---
services:
  app:
    container_name: mini-macros-app
    # TODO: change build to github link (see Docker Reference/Compose file reference/Compose Build Specification/Attributes)
    image: j4ck4L0up3/mini-macros-app:latest
    build:
      context: ./src/app
      dockerfile: Dockerfile.dev
    # TODO: change to 443 and have proxy route 8080 & 80 to that
    ports:
      - 8080:8080
    volumes:
      - ./src/app:/usr/src/app
    environment:
      - DB_SCHEMA_NAME=${DB_SCHEMA_NAME}
      - DB_ADMIN_USER=${DB_ADMIN_USER}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - SESSION_COOKIE_NAME=${SESSION_COOKIE_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - NO_REPLY_EMAIL_ADDRESS=${NO_REPLY_EMAIL_ADDRESS}
      - NO_REPLY_EMAIL_PASSWORD=${NO_REPLY_EMAIL_PASSWORD}
    depends_on:
      database:
        condition: service_healthy
    networks:
      - private

  database:
    container_name: mini-macros-db
    image: postgres:16.4
    restart: always
    shm_size: 128mB
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d dev"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - private

volumes:
  db-data:

networks:
  private:
    driver: bridge
