---
services:
  app:
    container_name: mini-macros-app
    # TODO: change build to github link (see Docker Reference/Compose file reference/Compose Build Specification/Attributes)
    image: j4ck4L0up3/mini-macros-app:latest
    build:
      context: ./src/app
      dockerfile: Dockerfile.dev
    env_file:
      - ./src/app/dev.env
    ports:
      - 8080:8080
    volumes:
      - ./src/app:/usr/src/app
    networks:
      - private

  database:
    container_name: mini-macros-db
    image: postgres:16
    # TODO: I actually don't know what restart does
    restart: always
    # limit database c
    shm_size: 128mB
    # set volume to create persistent database
    volumes:
      - db-data:/var/lib/postgresql/data
    secrets:
      - db_password
    environment:
      POSTGRES_DB: dev
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      ENV: development
    env_file:
      - ./database/scripts/.env
    ports:
      - 5432:5432
    networks:
      - private

volumes:
  db-data:

secrets:
  db_password:
    file: ./secrets/db_password.txt

networks:
  private:
    driver: bridge
