# syntax=docker/dockerfile:1

# get golang base image
FROM golang:1.22.5-alpine3.20 AS build-stage

# run for updates and install node for dependencies
RUN apk -U upgrade &&\
  apk add --no-cache make nodejs npm curl

# set working directory
WORKDIR /usr/src/app

# get go, templ, air dependencies
COPY go.mod go.sum ./
RUN go install github.com/a-h/templ/cmd/templ@latest &&\
  go install github.com/air-verse/air@latest
RUN go mod download && go mod verify

# setup frontend (htmx, tailwindcss) dependencies
RUN npm install -D tailwindcss &&\
  npm install @tailwindcss/forms &&\
  npm install @tailwindcss/typography

RUN npm install htmx.org@2.0.1

COPY . ./

CMD ["make", "dev"]
